// mkerrors.sh -m64
// MACHINE GENERATED BY THE COMMAND ABOVE; DO NOT EDIT

// Created by cgo -godefs - DO NOT EDIT
// cgo -godefs -- -m64 _const.go

package syscall

const (
	AF_APPLETALK              = 0x2
	AF_BLUETOOTH              = 0xa
	AF_DLI                    = 0x6
	AF_INET                   = 0x1
	AF_INET6                  = 0x5
	AF_IPX                    = 0x7
	AF_LINK                   = 0x4
	AF_LOCAL                  = 0x9
	AF_MAX                    = 0xb
	AF_NOTIFY                 = 0x8
	AF_ROUTE                  = 0x3
	AF_UNIX                   = 0x9
	AF_UNSPEC                 = 0x0
	B0                        = 0x0
	B110                      = 0x3
	B115200                   = 0x11
	B1200                     = 0x9
	B134                      = 0x4
	B150                      = 0x5
	B1800                     = 0xa
	B19200                    = 0xe
	B200                      = 0x6
	B230400                   = 0x12
	B2400                     = 0xb
	B300                      = 0x7
	B31250                    = 0x13
	B38400                    = 0xf
	B4800                     = 0xc
	B50                       = 0x1
	B57600                    = 0x10
	B600                      = 0x8
	B75                       = 0x2
	B9600                     = 0xd
	BRKINT                    = 0x2
	CLOCAL                    = 0x800
	CREAD                     = 0x80
	CS5                       = 0x0
	CS6                       = 0x0
	CS7                       = 0x0
	CS8                       = 0x20
	CSIZE                     = 0x20
	CSTOPB                    = 0x40
	ECHO                      = 0x8
	ECHOCTL                   = 0x400
	ECHOE                     = 0x10
	ECHOK                     = 0x20
	ECHOKE                    = 0x1000
	ECHONL                    = 0x40
	ECHOPRT                   = 0x800
	EV_BREAK                  = 0x2
	EV_CARRIER                = 0x4
	EV_CARRIERLOST            = 0x8
	EV_RING                   = 0x1
	FD_CLOEXEC                = 0x1
	FD_SETSIZE                = 0x400
	FLUSHO                    = 0x2000
	F_DUPFD                   = 0x1
	F_GETFD                   = 0x2
	F_GETFL                   = 0x8
	F_GETLK                   = 0x20
	F_LOCK                    = 0x1
	F_OK                      = 0x0
	F_RDLCK                   = 0x40
	F_SETFD                   = 0x4
	F_SETFL                   = 0x10
	F_SETLK                   = 0x80
	F_SETLKW                  = 0x100
	F_TEST                    = 0x3
	F_TLOCK                   = 0x2
	F_ULOCK                   = 0x0
	F_UNLCK                   = 0x200
	F_WRLCK                   = 0x400
	HUPCL                     = 0x400
	ICANON                    = 0x2
	ICRNL                     = 0x100
	IEXTEN                    = 0x200
	IFF_ALLMULTI              = 0x200
	IFF_AUTOUP                = 0x80
	IFF_AUTO_CONFIGURED       = 0x2000
	IFF_BROADCAST             = 0x2
	IFF_CONFIGURING           = 0x4000
	IFF_LINK                  = 0x1000
	IFF_LOOPBACK              = 0x8
	IFF_MULTICAST             = 0x8000
	IFF_NOARP                 = 0x40
	IFF_POINTOPOINT           = 0x10
	IFF_PROMISC               = 0x100
	IFF_SIMPLEX               = 0x800
	IFF_UP                    = 0x1
	IFNAMSIZ                  = 0x20
	IGNBRK                    = 0x1
	IGNCR                     = 0x80
	IGNPAR                    = 0x4
	INLCR                     = 0x40
	INPCK                     = 0x10
	IN_CLASSA_HOST            = 0xffffff
	IN_CLASSA_MAX             = 0x80
	IN_CLASSA_NET             = 0xff000000
	IN_CLASSA_NSHIFT          = 0x18
	IN_CLASSB_HOST            = 0xffff
	IN_CLASSB_MAX             = 0x10000
	IN_CLASSB_NET             = 0xffff0000
	IN_CLASSB_NSHIFT          = 0x10
	IN_CLASSC_HOST            = 0xff
	IN_CLASSC_NET             = 0xffffff00
	IN_CLASSC_NSHIFT          = 0x8
	IN_CLASSD_HOST            = 0xfffffff
	IN_CLASSD_NET             = 0xf0000000
	IN_CLASSD_NSHIFT          = 0x1c
	IN_LOOPBACKNET            = 0x7f
	IPPROTO_AH                = 0x33
	IPPROTO_DSTOPTS           = 0x3c
	IPPROTO_ESP               = 0x32
	IPPROTO_ETHERIP           = 0x61
	IPPROTO_FRAGMENT          = 0x2c
	IPPROTO_HOPOPTS           = 0x0
	IPPROTO_ICMP              = 0x1
	IPPROTO_ICMPV6            = 0x3a
	IPPROTO_IGMP              = 0x2
	IPPROTO_IP                = 0x0
	IPPROTO_IPV6              = 0x29
	IPPROTO_MAX               = 0x100
	IPPROTO_NONE              = 0x3b
	IPPROTO_RAW               = 0xff
	IPPROTO_ROUTING           = 0x2b
	IPPROTO_TCP               = 0x6
	IPPROTO_UDP               = 0x11
	IPV6_DEFHLIM              = 0x40
	IPV6_DSTOPTS              = 0x24
	IPV6_FLOWINFO_MASK        = 0xffffff0f
	IPV6_FLOWLABEL_MASK       = 0xffff0f00
	IPV6_FRAGTTL              = 0x78
	IPV6_HLIMDEC              = 0x1
	IPV6_HOPLIMIT             = 0x21
	IPV6_HOPOPTS              = 0x23
	IPV6_JOIN_GROUP           = 0x1c
	IPV6_LEAVE_GROUP          = 0x1d
	IPV6_MAXHLIM              = 0xff
	IPV6_MAXOPTHDR            = 0x800
	IPV6_MAXPACKET            = 0xffff
	IPV6_MMTU                 = 0x500
	IPV6_MULTICAST_HOPS       = 0x19
	IPV6_MULTICAST_IF         = 0x18
	IPV6_MULTICAST_LOOP       = 0x1a
	IPV6_PKTINFO              = 0x1f
	IPV6_RECVHOPLIMIT         = 0x22
	IPV6_RECVPKTINFO          = 0x20
	IPV6_RTHDR                = 0x25
	IPV6_UNICAST_HOPS         = 0x1b
	IPV6_V6ONLY               = 0x1e
	IPV6_VERSION              = 0x60
	IPV6_VERSION_MASK         = 0xf0
	IP_ADD_MEMBERSHIP         = 0xc
	IP_ADD_SOURCE_MEMBERSHIP  = 0x10
	IP_BLOCK_SOURCE           = 0xe
	IP_DF                     = 0x4000
	IP_DROP_MEMBERSHIP        = 0xd
	IP_DROP_SOURCE_MEMBERSHIP = 0x11
	IP_HDRINCL                = 0x2
	IP_MAXPACKET              = 0xffff
	IP_MAX_MEMBERSHIPS        = 0x14
	IP_MF                     = 0x2000
	IP_MSS                    = 0x240
	IP_MULTICAST_IF           = 0x9
	IP_MULTICAST_LOOP         = 0xb
	IP_MULTICAST_TTL          = 0xa
	IP_OFFMASK                = 0x1fff
	IP_OPTIONS                = 0x1
	IP_RECVDSTADDR            = 0x7
	IP_RECVOPTS               = 0x5
	IP_RECVRETOPTS            = 0x6
	IP_RETOPTS                = 0x8
	IP_TOS                    = 0x3
	IP_TTL                    = 0x4
	IP_UNBLOCK_SOURCE         = 0xf
	ISIG                      = 0x1
	ISTRIP                    = 0x20
	IXANY                     = 0x800
	IXOFF                     = 0x1000
	IXON                      = 0x400
	LOCK_EX                   = 0x2
	LOCK_NB                   = 0x4
	LOCK_SH                   = 0x1
	LOCK_UN                   = 0x8
	MAP_ANON                  = 0x8
	MAP_ANONYMOUS             = 0x8
	MAP_FIXED                 = 0x4
	MAP_PRIVATE               = 0x2
	MAP_SHARED                = 0x1
	MSG_BCAST                 = 0x100
	MSG_CTRUNC                = 0x20
	MSG_DONTROUTE             = 0x4
	MSG_DONTWAIT              = 0x80
	MSG_EOF                   = 0x400
	MSG_EOR                   = 0x8
	MSG_MCAST                 = 0x200
	MSG_OOB                   = 0x1
	MSG_PEEK                  = 0x2
	MSG_TRUNC                 = 0x10
	MSG_WAITALL               = 0x40
	MS_ASYNC                  = 0x1
	MS_INVALIDATE             = 0x4
	MS_SYNC                   = 0x2
	NAME_MAX                  = 0x100
	NOFLSH                    = 0x80
	OCRNL                     = 0x8
	OFDEL                     = 0x80
	OFILL                     = 0x40
	ONLCR                     = 0x4
	ONLRET                    = 0x20
	ONOCR                     = 0x10
	OPOST                     = 0x1
	O_ACCMODE                 = 0x3
	O_APPEND                  = 0x800
	O_CLOEXEC                 = 0x40
	O_CREAT                   = 0x200
	O_DIRECT                  = 0x100000
	O_DIRECTORY               = 0x200000
	O_DSYNC                   = 0x40000
	O_EXCL                    = 0x100
	O_NDELAY                  = 0x80
	O_NOCACHE                 = 0x100000
	O_NOCTTY                  = 0x1000
	O_NOFOLLOW                = 0x80000
	O_NONBLOCK                = 0x80
	O_NOTRAVERSE              = 0x2000
	O_RDONLY                  = 0x0
	O_RDWR                    = 0x2
	O_RSYNC                   = 0x20000
	O_RWMASK                  = 0x3
	O_SYNC                    = 0x10000
	O_TRUNC                   = 0x400
	O_WRONLY                  = 0x1
	PARENB                    = 0x100
	PARMRK                    = 0x8
	PARODD                    = 0x200
	PENDIN                    = 0x4000
	PRIO_PGRP                 = 0x1
	PRIO_PROCESS              = 0x0
	PRIO_USER                 = 0x2
	PROT_EXEC                 = 0x4
	PROT_NONE                 = 0x0
	PROT_READ                 = 0x1
	PROT_WRITE                = 0x2
	RLIMIT_AS                 = 0x6
	RLIMIT_CORE               = 0x0
	RLIMIT_CPU                = 0x1
	RLIMIT_DATA               = 0x2
	RLIMIT_FSIZE              = 0x3
	RLIMIT_NOFILE             = 0x4
	RLIMIT_STACK              = 0x5
	RLIM_INFINITY             = 0xffffffff
	RTF_BLACKHOLE             = 0x1000
	RTF_DEFAULT               = 0x80
	RTF_DYNAMIC               = 0x10
	RTF_GATEWAY               = 0x2
	RTF_HOST                  = 0x4
	RTF_LOCAL                 = 0x200000
	RTF_MODIFIED              = 0x20
	RTF_REJECT                = 0x8
	RTF_STATIC                = 0x800
	RTF_UP                    = 0x1
	RUSAGE_CHILDREN           = -0x1
	RUSAGE_SELF               = 0x0
	SCM_RIGHTS                = 0x1
	SHUT_RD                   = 0x0
	SHUT_RDWR                 = 0x2
	SHUT_WR                   = 0x1
	SOCK_DGRAM                = 0x2
	SOCK_MISC                 = 0xff
	SOCK_RAW                  = 0x3
	SOCK_SEQPACKET            = 0x5
	SOCK_STREAM               = 0x1
	SOL_SOCKET                = -0x1
	SOMAXCONN                 = 0x20
	SO_ACCEPTCONN             = 0x1
	SO_BINDTODEVICE           = 0x4000000a
	SO_BROADCAST              = 0x2
	SO_DEBUG                  = 0x4
	SO_DONTROUTE              = 0x8
	SO_ERROR                  = 0x40000007
	SO_KEEPALIVE              = 0x10
	SO_LINGER                 = 0x200
	SO_NONBLOCK               = 0x40000009
	SO_OOBINLINE              = 0x20
	SO_PEERCRED               = 0x4000000b
	SO_RCVBUF                 = 0x40000004
	SO_RCVLOWAT               = 0x40000005
	SO_RCVTIMEO               = 0x40000006
	SO_REUSEADDR              = 0x40
	SO_REUSEPORT              = 0x80
	SO_SNDBUF                 = 0x40000001
	SO_SNDLOWAT               = 0x40000002
	SO_SNDTIMEO               = 0x40000003
	SO_TYPE                   = 0x40000008
	SO_USELOOPBACK            = 0x100
	S_ALLOW_DUPS              = 0x80000
	S_ATTR                    = 0x10000000
	S_ATTR_DIR                = 0x8000000
	S_DOUBLE_INDEX            = 0x40000
	S_FLOAT_INDEX             = 0x800000
	S_IEXEC                   = 0x40
	S_IFBLK                   = 0x6000
	S_IFCHR                   = 0x2000
	S_IFDIR                   = 0x4000
	S_IFIFO                   = 0x1000
	S_IFLNK                   = 0xa000
	S_IFMT                    = 0xf000
	S_IFREG                   = 0x8000
	S_IFSOCK                  = 0xc000
	S_INDEX_DIR               = 0x20000000
	S_INT_INDEX               = 0x2000000
	S_IREAD                   = 0x100
	S_IRGRP                   = 0x20
	S_IROTH                   = 0x4
	S_IRUSR                   = 0x100
	S_IRWXG                   = 0x38
	S_IRWXO                   = 0x7
	S_IRWXU                   = 0x1c0
	S_ISGID                   = 0x400
	S_ISUID                   = 0x800
	S_ISVTX                   = 0x200
	S_IUMSK                   = 0xfff
	S_IWGRP                   = 0x10
	S_IWOTH                   = 0x2
	S_IWRITE                  = 0x80
	S_IWUSR                   = 0x80
	S_IXGRP                   = 0x8
	S_IXOTH                   = 0x1
	S_IXUSR                   = 0x40
	S_LINK_AUTO_DELETE        = 0x80000
	S_LINK_SELF_HEALING       = 0x40000
	S_LONG_LONG_INDEX         = 0x200000
	S_STR_INDEX               = 0x1000000
	S_UINT_INDEX              = 0x4000000
	S_ULONG_LONG_INDEX        = 0x400000
	TCFLSH                    = 0x8006
	TCIFLUSH                  = 0x1
	TCIOFLUSH                 = 0x3
	TCOFLUSH                  = 0x2
	TCP_MAXSEG                = 0x2
	TCP_NODELAY               = 0x1
	TCP_NOOPT                 = 0x8
	TCP_NOPUSH                = 0x4
	TCSAFLUSH                 = 0x4
	TIOCCBRK                  = 0x8015
	TIOCGPGRP                 = 0x800f
	TIOCGWINSZ                = 0x800c
	TIOCMGET                  = 0x8012
	TIOCMSET                  = 0x8013
	TIOCM_CD                  = 0x8
	TIOCM_CTS                 = 0x1
	TIOCM_DSR                 = 0x2
	TIOCM_DTR                 = 0x10
	TIOCM_RI                  = 0x4
	TIOCM_RTS                 = 0x20
	TIOCSBRK                  = 0x8014
	TIOCSCTTY                 = 0x8011
	TIOCSPGRP                 = 0x8010
	TIOCSWINSZ                = 0x800d
	TOSTOP                    = 0x100
	VEOF                      = 0x4
	VEOL                      = 0x5
	VEOL2                     = 0x6
	VERASE                    = 0x2
	VINTR                     = 0x0
	VKILL                     = 0x3
	VMIN                      = 0x4
	VQUIT                     = 0x1
	VSTART                    = 0x8
	VSTOP                     = 0x9
	VSUSP                     = 0xa
	VSWTCH                    = 0x7
	VT0                       = 0x0
	VT1                       = 0x4000
	VTDLY                     = 0x4000
	VTIME                     = 0x5
)

// Errors
const (
	E2BIG           = Errno(-0x7fff8fff & 0xffffffff)
	EACCES          = Errno(-0x7ffffffe & 0xffffffff)
	EADDRINUSE      = Errno(-0x7fff8fea & 0xffffffff)
	EADDRNOTAVAIL   = Errno(-0x7fff8fe9 & 0xffffffff)
	EAFNOSUPPORT    = Errno(-0x7fff8feb & 0xffffffff)
	EAGAIN          = Errno(-0x7ffffff5 & 0xffffffff)
	EALREADY        = Errno(-0x7fff8fdb & 0xffffffff)
	EBADF           = Errno(-0x7fffa000 & 0xffffffff)
	EBADMSG         = Errno(-0x7fff8fd2 & 0xffffffff)
	EBUSY           = Errno(-0x7ffffff2 & 0xffffffff)
	ECANCELED       = Errno(-0x7fff8fd1 & 0xffffffff)
	ECHILD          = Errno(-0x7fff8ffe & 0xffffffff)
	ECONNABORTED    = Errno(-0x7fff8fe5 & 0xffffffff)
	ECONNREFUSED    = Errno(-0x7fff8fe0 & 0xffffffff)
	ECONNRESET      = Errno(-0x7fff8fe4 & 0xffffffff)
	EDEADLK         = Errno(-0x7fff8ffd & 0xffffffff)
	EDESTADDRREQ    = Errno(-0x7fff8fd0 & 0xffffffff)
	EDOM            = Errno(-0x7fff8ff0 & 0xffffffff)
	EDOOFUS         = Errno(-0x7ffffffb & 0xffffffff)
	EDQUOT          = Errno(-0x7fff8fcf & 0xffffffff)
	EEXIST          = Errno(-0x7fff9ffe & 0xffffffff)
	EFAULT          = Errno(-0x7fffecff & 0xffffffff)
	EFBIG           = Errno(-0x7fff8ffc & 0xffffffff)
	EFPOS           = Errno(-0x7fff8ff2 & 0xffffffff)
	EHOSTDOWN       = Errno(-0x7fff8fd3 & 0xffffffff)
	EHOSTUNREACH    = Errno(-0x7fff8fdf & 0xffffffff)
	EIDRM           = Errno(-0x7fff8fce & 0xffffffff)
	EILSEQ          = Errno(-0x7fff8fda & 0xffffffff)
	EINPROGRESS     = Errno(-0x7fff8fdc & 0xffffffff)
	EINTR           = Errno(-0x7ffffff6 & 0xffffffff)
	EINVAL          = Errno(-0x7ffffffb & 0xffffffff)
	EIO             = Errno(-0x7fffffff & 0xffffffff)
	EISCONN         = Errno(-0x7fff8fe3 & 0xffffffff)
	EISDIR          = Errno(-0x7fff9ff7 & 0xffffffff)
	ELOOP           = Errno(-0x7fff9ff4 & 0xffffffff)
	EMFILE          = Errno(-0x7fff9ff6 & 0xffffffff)
	EMLINK          = Errno(-0x7fff8ffb & 0xffffffff)
	EMSGSIZE        = Errno(-0x7fff8fd6 & 0xffffffff)
	EMULTIHOP       = Errno(-0x7fff8fcd & 0xffffffff)
	ENAMETOOLONG    = Errno(-0x7fff9ffc & 0xffffffff)
	ENETDOWN        = Errno(-0x7fff8fe8 & 0xffffffff)
	ENETRESET       = Errno(-0x7fff8fe6 & 0xffffffff)
	ENETUNREACH     = Errno(-0x7fff8fe7 & 0xffffffff)
	ENFILE          = Errno(-0x7fff8ffa & 0xffffffff)
	ENOATTR         = Errno(-0x7fff8fc4 & 0xffffffff)
	ENOBUFS         = Errno(-0x7fff8fdd & 0xffffffff)
	ENODATA         = Errno(-0x7fff8fcc & 0xffffffff)
	ENODEV          = Errno(-0x7fff8ff9 & 0xffffffff)
	ENOENT          = Errno(-0x7fff9ffd & 0xffffffff)
	ENOERR          = Errno(0x0 & 0xffffffff)
	ENOEXEC         = Errno(-0x7fffecfe & 0xffffffff)
	ENOLCK          = Errno(-0x7fff8ff8 & 0xffffffff)
	ENOLINK         = Errno(-0x7fff8fcb & 0xffffffff)
	ENOMEM          = Errno(-0x80000000 & 0xffffffff)
	ENOMSG          = Errno(-0x7fff8fd9 & 0xffffffff)
	ENOPROTOOPT     = Errno(-0x7fff8fde & 0xffffffff)
	ENOSPC          = Errno(-0x7fff9ff9 & 0xffffffff)
	ENOSR           = Errno(-0x7fff8fca & 0xffffffff)
	ENOSTR          = Errno(-0x7fff8fc9 & 0xffffffff)
	ENOSYS          = Errno(-0x7fff8ff7 & 0xffffffff)
	ENOTCONN        = Errno(-0x7fff8fe2 & 0xffffffff)
	ENOTDIR         = Errno(-0x7fff9ffb & 0xffffffff)
	ENOTEMPTY       = Errno(-0x7fff9ffa & 0xffffffff)
	ENOTSOCK        = Errno(-0x7fff8fd4 & 0xffffffff)
	ENOTSUP         = Errno(-0x7fff8fc8 & 0xffffffff)
	ENOTTY          = Errno(-0x7fff8ff6 & 0xffffffff)
	ENXIO           = Errno(-0x7fff8ff5 & 0xffffffff)
	EOK             = Errno(0x0 & 0xffffffff)
	EOPNOTSUPP      = Errno(-0x7fff8fd5 & 0xffffffff)
	EOVERFLOW       = Errno(-0x7fff8fd7 & 0xffffffff)
	EPERM           = Errno(-0x7ffffff1 & 0xffffffff)
	EPFNOSUPPORT    = Errno(-0x7fff8fec & 0xffffffff)
	EPIPE           = Errno(-0x7fff9ff3 & 0xffffffff)
	EPROTO          = Errno(-0x7fff8fc7 & 0xffffffff)
	EPROTONOSUPPORT = Errno(-0x7fff8fed & 0xffffffff)
	EPROTOTYPE      = Errno(-0x7fff8fee & 0xffffffff)
	ERANGE          = Errno(-0x7fff8fef & 0xffffffff)
	EROFS           = Errno(-0x7fff9ff8 & 0xffffffff)
	ESHUTDOWN       = Errno(-0x7fff8fe1 & 0xffffffff)
	ESIGPARM        = Errno(-0x7fff8ff1 & 0xffffffff)
	ESPIPE          = Errno(-0x7fff8ff4 & 0xffffffff)
	ESRCH           = Errno(-0x7fff8ff3 & 0xffffffff)
	ESTALE          = Errno(-0x7fff8fd8 & 0xffffffff)
	ETIME           = Errno(-0x7fff8fc6 & 0xffffffff)
	ETIMEDOUT       = Errno(-0x7ffffff7 & 0xffffffff)
	ETXTBSY         = Errno(-0x7fff8fc5 & 0xffffffff)
	EWOULDBLOCK     = Errno(-0x7ffffff5 & 0xffffffff)
	EXDEV           = Errno(-0x7fff9ff5 & 0xffffffff)
)

// Signals
const (
	SIGABRT      = Signal(0x6)
	SIGALRM      = Signal(0xe)
	SIGBUS       = Signal(0x1e)
	SIGCHLD      = Signal(0x5)
	SIGCONT      = Signal(0xc)
	SIGFPE       = Signal(0x8)
	SIGHUP       = Signal(0x1)
	SIGILL       = Signal(0x4)
	SIGINT       = Signal(0x2)
	SIGKILL      = Signal(0x9)
	SIGKILLTHR   = Signal(0x15)
	SIGPIPE      = Signal(0x7)
	SIGPOLL      = Signal(0x17)
	SIGPROF      = Signal(0x18)
	SIGQUIT      = Signal(0x3)
	SIGRESERVED1 = Signal(0x1f)
	SIGRESERVED2 = Signal(0x20)
	SIGSEGV      = Signal(0xb)
	SIGSTOP      = Signal(0xa)
	SIGSYS       = Signal(0x19)
	SIGTERM      = Signal(0xf)
	SIGTRAP      = Signal(0x16)
	SIGTSTP      = Signal(0xd)
	SIGTTIN      = Signal(0x10)
	SIGTTOU      = Signal(0x11)
	SIGURG       = Signal(0x1a)
	SIGUSR1      = Signal(0x12)
	SIGUSR2      = Signal(0x13)
	SIGVTALRM    = Signal(0x1b)
	SIGWINCH     = Signal(0x14)
	SIGXCPU      = Signal(0x1c)
	SIGXFSZ      = Signal(0x1d)
)

// Error table
var errors = [...]string{
	1:     "out of memory",
	2:     "I/O error",
	3:     "permission denied",
	6:     "invalid Argument",
	10:    "operation timed out",
	11:    "interrupted system call",
	12:    "operation would block",
	15:    "device/File/Resource busy",
	16:    "operation not allowed",
	4866:  "bad address",
	4867:  "not an executable",
	24577: "bad file descriptor",
	24579: "file or Directory already exists",
	24580: "no such file or directory",
	24581: "file name too long",
	24582: "not a directory",
	24583: "directory not empty",
	24584: "no space left on device",
	24585: "read-only file system",
	24586: "is a directory",
	24587: "too many open files",
	24588: "cross-device link",
	24589: "too many symbolic links",
	24590: "broken pipe",
	28674: "argument too big",
	28675: "no child process",
	28676: "resource deadlock",
	28677: "file too large",
	28678: "too many links",
	28679: "file table overflow",
	28680: "no such device",
	28681: "no record locks available",
	28682: "function not implemented",
	28683: "not a tty",
	28684: "device not accessible",
	28685: "seek not allowed on file descriptor",
	28686: "no such process",
	28687: "file Position Error",
	28688: "signal Error",
	28689: "numerical argument out of range",
	28690: "range Error",
	28691: "protocol wrong type for socket",
	28692: "protocol not supported",
	28693: "protocol family not supported",
	28694: "address family not supported by protocol family",
	28695: "address already in use",
	28696: "can't assign requested address",
	28697: "network is down",
	28698: "network is unreachable",
	28699: "network dropped connection on reset",
	28700: "software caused connection abort",
	28701: "connection reset by peer",
	28702: "socket is already connected",
	28703: "socket is not connected",
	28704: "can't send after socket shutdown",
	28705: "connection refused",
	28706: "no route to host",
	28707: "protocol option not available",
	28708: "no buffer space available",
	28709: "operation now in progress",
	28710: "operation already in progress",
	28711: "illegal byte sequence",
	28712: "no message of desired type",
	28713: "stale file handle",
	28714: "value too large for defined type",
	28715: "message too long",
	28716: "operation not supported",
	28717: "socket operation on non-socket",
	28718: "unknown POSIX Error (-2147454931)",
	28719: "bad message",
	28720: "operation canceled",
	28721: "destination address required",
	28722: "reserved",
	28723: "identifier removed",
	28724: "reserved",
	28725: "no message available",
	28726: "reserved",
	28727: "no STREAM resources",
	28728: "not a STREAM",
	28729: "not supported",
	28730: "protocol error",
	28731: "STREAM ioctl() timeout",
	28732: "text file busy",
	28733: "no such attribute",
	0:     "no error",
}

// Signal table
var signals = [...]string{
	1:  "hangup",
	2:  "interrupt",
	3:  "quit",
	4:  "illegal instruction",
	5:  "child exited",
	6:  "abort",
	7:  "broken pipe",
	8:  "floating point exception",
	9:  "killed (by death)",
	10: "stopped",
	11: "segmentation violation",
	12: "continued",
	13: "stopped (tty output)",
	14: "alarm",
	15: "termination requested",
	16: "stopped (tty input)",
	17: "stopped (tty output)",
	18: "user defined signal 1",
	19: "user defined signal 2",
	20: "window size changed",
	21: "kill Thread",
	22: "trace/breakpoint trap",
	23: "pollable event",
	24: "profiling timer expired",
	25: "bad system call",
	26: "high bandwidth data is available at socket",
	27: "virtual timer expired",
	28: "CPU time limit exceeded",
	29: "file size limit exceeded",
	30: "bus error",
	31: "reserved signal 1",
	32: "reserved signal 2",
}
